FROM mcr.microsoft.com/powershell:latest

# Note: The DEBIAN_FRONTEND export avoids warnings when you go on to work with your container.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git curl \
    && apt-get clean

RUN pwsh -Command "Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted; Install-Module -Name powershell-yaml -Scope AllUsers -Repository PSGallery -Force -AcceptLicense"

RUN  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN  curl -LO "https://github.com/siderolabs/talos/releases/download/v1.7.4/talosctl-linux-amd64" \
    && install -o root -g root -m 0755 talosctl-linux-amd64 /usr/local/bin/talosctl