FROM mcr.microsoft.com/powershell:latest

# https://github.com/siderolabs/talos/releases
ARG TALOS_VERSION="1.7.4"
# https://dl.k8s.io/release/stable.txt
ARG KUBECTL_VERSION="1.30.1"
# https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
ARG CILIUM_CLI_VERSION="0.16.9"
# https://github.com/helm/helm/releases
ARG HELM_VERSION="3.15.1"

# Note: The DEBIAN_FRONTEND export avoids warnings when you go on to work with your container.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git curl \
    && apt-get clean

RUN pwsh -Command "Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted; Install-Module -Name powershell-yaml -Scope AllUsers -Repository PSGallery -Force -AcceptLicense"

RUN  curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN  curl -LO "https://github.com/siderolabs/talos/releases/download/v${TALOS_VERSION}/talosctl-linux-amd64" \
    && install -o root -g root -m 0755 talosctl-linux-amd64 /usr/local/bin/talosctl

RUN  curl -LO  "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" \
    && tar -zxvf helm-v${HELM_VERSION}-linux-amd64.tar.gz \
    && install -o root -g root -m 0755 linux-amd64/helm /usr/local/bin/helm

RUN curl -LO "https://github.com/cilium/cilium-cli/releases/download/v${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz" \
    && tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin \
    && rm cilium-linux-amd64.tar.gz
    